// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNpVY3U3qDLS8PLg6UW9A2kfS8yMEN2k',
    appId: '1:1047436820658:web:293738a074fc8db84009ab',
    messagingSenderId: '1047436820658',
    projectId: 'order-3d59e',
    authDomain: 'order-3d59e.firebaseapp.com',
    storageBucket: 'order-3d59e.appspot.com',
    measurementId: 'G-J3R9F4S1PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4tOs2nei6TMpNFyI7E6goY42rW9qop8',
    appId: '1:1047436820658:android:ad8678fb6a22489f4009ab',
    messagingSenderId: '1047436820658',
    projectId: 'order-3d59e',
    storageBucket: 'order-3d59e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEI-sNW7YFSggSfI7oglH1KlTOlxLr7g',
    appId: '1:1047436820658:ios:cfc08197f03a44eb4009ab',
    messagingSenderId: '1047436820658',
    projectId: 'order-3d59e',
    storageBucket: 'order-3d59e.appspot.com',
    iosBundleId: 'com.example.odPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACEI-sNW7YFSggSfI7oglH1KlTOlxLr7g',
    appId: '1:1047436820658:ios:cfc08197f03a44eb4009ab',
    messagingSenderId: '1047436820658',
    projectId: 'order-3d59e',
    storageBucket: 'order-3d59e.appspot.com',
    iosBundleId: 'com.example.odPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSNpVY3U3qDLS8PLg6UW9A2kfS8yMEN2k',
    appId: '1:1047436820658:web:f13b3e685d9877cc4009ab',
    messagingSenderId: '1047436820658',
    projectId: 'order-3d59e',
    authDomain: 'order-3d59e.firebaseapp.com',
    storageBucket: 'order-3d59e.appspot.com',
    measurementId: 'G-LM0F1X5WSB',
  );
}
